name: Github Page

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - run: cd ./ui && npm install && npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}